### PR TITLE
removing axios, redux

### LINKED ISSUE #33: Split up React components
All of the React components we're using right now are in [App.js](https://github.com/mjec/rc-niceties/blob/b75d69fc55bd99d04ce3a0557798b1fb249bd0f6/src/App.js), and as a result, that file is some 700 lines long. Let's move the components out to their own files and import them appropriately, so as to make the front-end source code easier to navigate.

### PR DESCRIPTION
**Pull request by christalee**
This involves moving a lot of code around, almost entirely unchanged. I did change `updated_niceties` to a prop, passed from People to Person; please feel free to check my work there. I deleted a line in Person, `while (updated_niceties_spinlock) {}`, is that crucial to anything?

Closes #33

### CODE REVIEW

**Review by jasonaowen — CHANGES_REQUESTED** [review]
Thanks for working on this, @christalee!

It sounds like splitting the React components out into separate files was a bit more difficult than I'd initially guessed! Sorry about that.

> I deleted a line in Person, `while (updated_niceties_spinlock) {}`, is that crucial to anything?

At a low level, that sure looks like a [spinlock](https://en.wikipedia.org/wiki/Spinlock), and while busywaiting is a pattern we probably don't want in the front end, I don't think we can just remove that line. If nothing else, we'd also need to remove the other references to `updated_niceties_spinlock`, but I think we'd also want to replace it with some other kind of lock or prop to prevent inconsistent state in local storage. (Which I think is what that lock is protecting? It was introduced in commit fa200173; maybe @mjec can say more.)

At a high level, I see now that you probably deleted that line because it is in `Person` and the other references to `updated_niceties_spinlock` are in `People`. That's definitely a complication I didn't consider, and I think for this first iteration, it makes sense to keep `Person` and `People` together in `App.js`, at least until that code is refactored a bit.

> This involves moving a lot of code around, almost entirely unchanged.

In general, I've found that it's much easier to review code (both while looking at a pull request and, later, when trying to understand why the code is the way it is) when each commit is whole and self contained, and limited to a single logical change. Git might be able to figure out that the React components are being moved if the additions and deletions are part of the same commit, which in turn can help with `git blame`; it definitely won't be able to if they're in separate commits.

I've also found that it's much easier to review code where moves are the entire commit, and changes are in separate commits. When a bunch of code is deleted, and a bunch of code is added, and those are not the same, it gets much more difficult to figure out what changed - particularly for a human.

Finally, when a commit says "thing is broken", and the commit immediately following it says "fixed thing", that's usually a sign that those two commits are not split up ideally.

I'm asking for a bit of git work, but I think there are a bunch of changes and I'd like to make sure each gets reviewed appropriately. I think it'd be useful to have a separate commit for each of these:

- add your SCHEMA.md notes
- remove unused code in `src/actions/index.js`
- remove unused dependencies
- remove unused `Nicety` component
- move each component out to its own file:
  - `SaveButton`
  - `PeopleRow`
  - `NicetyRow`
  - `NicetyDisplay`
  - `Nicety`
  - `Admin`
  - `AdminNicety`
- (maybe) refactor `updated_niceties` into a prop
- (maybe) refactor `updated_niceties_spinlock`
- if the previous two,
  - move `Person` out to its own file
  - move `People` out to its own file

Each of those commits should be pretty small. In my experience, many small commits are way way easier to review than a few large commits!

**Comment by christalee** [comment]
Ok, I think I've broken down the changes into a set of commits that should be easier to review, give or take some punctuation. I did the refactoring for `updated_niceties` and `updated_niceties_spinlock`.

**Comment by jasonaowen** [comment]
Thank you for splitting this up, @christalee! I'm still only partway through reviewing; in particular, 0ef80c6 is a big change that I'm slowly working my way through.

I also glanced at c1df876, which moves the spinlock to a property. I'll need to refresh myself on the React lifecycle, but I am at least slightly worried that there are non-obvious consequences to making it a prop. Were you able to figure out how to trigger that code? How should I test that?

**Comment by christalee** [comment]
re: `c1df876`, I inserted some console.log statements in People and Person to confirm that the spinlock behaves as the code suggests it should, and I figured out that in Person, it should call `this.props.spinlock` rather than `this.props.updated_niceties_spinlock`. 

My understanding is that the spinlock prevents any changes being registered to text or checkboxes while `People.saveAllComments` is processing `updated_niceties`. I considered adding a delay but couldn't figure out where to put it. Is there a non-trivial way to test this?

**Comment by christalee** [comment]
I'm sorry `0ef80c6` is such trouble; I would've said I didn't change much there, but I must've changed enough to confuse the diff algorithm.

Upon further thought, I think you're right that making the spinlock a prop is a bad idea. Would you like me to undo that change by making an additional commit, or force-pushing an updated set of changes? Or some other thing?

**Comment by jasonaowen** [comment]
I'm sorry I haven't been able to dedicate the time to this PR that it deserves.

It looks like your editor "helpfully" reformatted the code you moved, which prevents git from [detecting moved code](https://coderwall.com/p/x8xbnq/git-don-t-blame-people-for-changing-whitespaces-or-moving-code); running `git blame -M -C -- src/components/SaveButton.js` (to pick a file at random) shows that you are the author for all those lines, which obscures the history.

To make sure that what I'm asking is possible, I recreated one of your commits at https://github.com/mjec/rc-niceties/commit/f41d3e8a53a915cc9c83c4093544f0299465f6b7 , ran `git blame -M -C src/components/save-button.js`, and saw the history I was hoping for.

> Upon further thought, I think you're right that making the spinlock a prop is a bad idea.

Given this, I think it makes sense to roll back the branch to 344e2fe (`git push -f origin 344e2fe:components` or so); that'll leave this as a useful, small, and easily-merged PR. If you want to work with the separated components, please go back through and move them out, one per commit as you did before, being careful to keep the formatting the same and making sure that the application still builds after each commit. Please don't feel obligated, though, because this was meant as some low hanging fruit and I'm sorry it turned out to be so fraught!

**Comment by christalee** [comment]
Ok, I've rolled back the branch so the only changes are removing axios and redux as dependencies and deleting empty files. I'll think about how to handle the component situation; I do think it'll be easier to work with as separate files. But I might need to take a deep breath before tackling it again. Thanks for working through this with me!

**Review by jasonaowen — APPROVED** [review]
Thank you so much, @christalee! :blue_heart:

**Pull request merged**
