### PR TITLE
enhancements: remove edit/review functionality for admins, img title text

### PR DESCRIPTION
**Pull request by christalee**
This PR includes a migration of AdminNicety from a class to a functional component, and a simplification of the props passed into it in Admin. I realized this was possible once I removed code related to editing and reviewing niceties, since we've been informed that's not really a use-case for admins.

I also added the user's full name as a title (hover-text) for each photo, in case there are two Sams in your batch and you can't quite recall which is which.

### CODE REVIEW

**Comment by jasonaowen** [comment]
Can you please rebase this onto `main`, @christalee? I see a merge commit, and suspect that might be complicating matters.

If that turns out to be a red herring, can you please look into why there are 20k lines changed in `package-lock.json`? For example, it appears that eslint is being downgraded from 7.29.0 to 4.10.0, which is probably not what we want!

**Comment by christalee** [comment]
I rebased onto main but then there was a merge conflict in AdminNicety.js so now there's a new one. I'm not sure what's going on with package-lock.json but I did notice that it previously included a dependency on `"eslint-plugin-react": "^7.22.0",` which has been removed / was probably an error. One option is to revert to the version of package-lock.json from [75a757](https://github.com/mjec/rc-niceties/commit/75a757c8dcb51543dd9a6a5429e8f2897c20a3d1) and downgrade my local npm to v.6.x to match yours. (I'm currently on 7.10.0) What do you think?

**Comment by jasonaowen** [comment]
I'm not clear on why this PR is making any changes to `package-lock.json`, as there are no corresponding changes to `package.json`. I don't think you need to downgrade to npm 6 and revert ac8b248063c4eecd6030cf3b4c30776516e88915, though!

The merge conflict appears to be with a [change](https://github.com/mjec/rc-niceties/pull/83/commits/fe9418706cd255f34d067b2f8e7a83e2406d6281#diff-362564325b6e4f56d9c5d71318b030d5af487dd6763563fe77333197c62bced1R6-R11) made in #83. You'll need to resolve the merge conflict while rebasing, but using the take-mine strategy should work fine; that is, I think you can just delete the conflict markers and the #83-version, without needing to modify your proposed changes.

**Comment by christalee** [comment]
I discarded all the changes to package-lock.json and rebased and all should be well now. Thanks for talking me through it @jasonaowen !

**Review by jasonaowen — APPROVED** [review]
This looks good to me! Thank you, @christalee!

**Pull request merged**
