### PR TITLE
linting & removing unused code

### PR DESCRIPTION
**Pull request by christalee**
At @jasonaowen 's suggestion, code has been formatted with flake8 and ESLint. Also I deleted some code that was commented out already.
Mega apologies for accidentally pushing these straight to master instead of making a pull request.

### CODE REVIEW

**Comment by mjec** [comment]
> Mega apologies for accidentally pushing these straight to master instead of making a pull request.

No worries at all! This change LGTM, and you should absolutely feel empowered to push straight to master if you'd like

**Comment by mjec** [comment]
Also FYI @christalee I've just enabled automatic deploys from master, but there's an issue with `react-scripts build`. I'll try to investigate more this weekend, but let me know if you'd like access to the heroku instance to debug.

**Comment by christalee** [comment]
Thanks so much @mjec ! I definitely have my hands full with updating the codebase without grappling with the Heroku deployment as well, I have zero experience with that sort of thing. But if you don't have time to look into it (sounds like you do now, but in the future), I can try to figure it out.

**Comment by mjec** [comment]
Great, thanks @christalee! I've just added you and @jasonaowen to the Heroku account using your email addresses in the RC directory. Let me know if you run into any trouble accessing it.

**Comment by jasonaowen** [comment]
Got it, @mjec - thank you!

**Pull request merged**
